# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'es_connector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(787, 710)
        self.Host = QtWidgets.QLineEdit(Dialog)
        self.Host.setGeometry(QtCore.QRect(90, 10, 113, 25))
        self.Host.setInputMask("")
        self.Host.setMaxLength(32767)
        self.Host.setObjectName("Host")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 88, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(253, 200, 88, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(350, 10, 431, 581))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(13, 14, 66, 17))
        self.label_2.setObjectName("label_2")
        self.Host_2 = QtWidgets.QLineEdit(Dialog)
        self.Host_2.setGeometry(QtCore.QRect(89, 46, 41, 25))
        self.Host_2.setInputMask("")
        self.Host_2.setMaxLength(32767)
        self.Host_2.setObjectName("Host_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(12, 50, 66, 17))
        self.label_3.setObjectName("label_3")
        self.Host_3 = QtWidgets.QLineEdit(Dialog)
        self.Host_3.setGeometry(QtCore.QRect(88, 86, 251, 25))
        self.Host_3.setInputMask("")
        self.Host_3.setMaxLength(32767)
        self.Host_3.setObjectName("Host_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(11, 90, 66, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(260, 14, 81, 17))
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 240, 331, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.Host_4 = QtWidgets.QLineEdit(Dialog)
        self.Host_4.setGeometry(QtCore.QRect(87, 166, 251, 25))
        self.Host_4.setInputMask("")
        self.Host_4.setText("")
        self.Host_4.setMaxLength(32767)
        self.Host_4.setObjectName("Host_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 71, 17))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 590, 761, 111))
        self.label.setObjectName("label")
        self.Host_5 = QtWidgets.QLineEdit(Dialog)
        self.Host_5.setGeometry(QtCore.QRect(87, 126, 251, 25))
        self.Host_5.setInputMask("")
        self.Host_5.setText("")
        self.Host_5.setMaxLength(32767)
        self.Host_5.setObjectName("Host_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 71, 17))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Host.setToolTip(_translate("Dialog", "Host"))
        self.Host.setText(_translate("Dialog", "127.0.0.1"))
        self.pushButton.setText(_translate("Dialog", "Connect"))
        self.pushButton_2.setText(_translate("Dialog", "Run Query"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  &quot;size&quot;: 100, </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  &quot;query&quot;: {</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    &quot;match_all&quot;: {}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  }</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">}</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Host"))
        self.Host_2.setToolTip(_translate("Dialog", "Host"))
        self.Host_2.setText(_translate("Dialog", "9200"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.Host_3.setToolTip(_translate("Dialog", "Host"))
        self.Host_3.setText(_translate("Dialog", "index_name"))
        self.label_4.setText(_translate("Dialog", "Index"))
        self.label_5.setText(_translate("Dialog", "DSL Query"))
        self.Host_4.setToolTip(_translate("Dialog", "Host"))
        self.label_6.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#1c71d8;\">Note</span>:</p><p><span style=\" font-size:9pt;\">Provide username and password only if your server needs it</span></p><p><span style=\" font-size:9pt;\">Provide a valid query (can be validated using kibana)</span></p><p><span style=\" font-size:9pt;\">The data load will depend upon the size of data fetched and your machine\'s compute power</span></p></body></html>"))
        self.Host_5.setToolTip(_translate("Dialog", "Host"))
        self.label_7.setText(_translate("Dialog", "Username"))
